# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bad12fe07f37c2002eb32f1eee8c30774365641ecac8b9a6f7d7dd47e80bad6d2ccc5abaa59d7ff44be4bf2bf669a6ff9aa69c118cbe3a5db6979d15da668ac

test:
  secret_key_base: f1fcc1258c643769dd171edf5942f53678ebeadd17ab1b260e17adcae9c1472a5bd54e1ded703eaef584157cd48ab70ba43f5b82b5986d1302e6afab2bfca281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
